[discord]
# Discord bot token, details at https://discord.com/developers/docs/topics/oauth2
token=
# The "operators" (limited user) of this bot, specified via Discord user ID
operators=[]
# The "owners" (full users) of this bot, specified via Discord user ID
owners=[]

[server]
# Path to the piqueserver/config/ folder
cfg_path=
# Name of the Docker process piqueserver is running inside of
name=
# IP people can connect to your server through (just for show)
ip=